export const services = [
    {
      id: 1,
      name: "ابر النضارة للوجه والبشرة",
      type: "cosmetics",
      price: 350,
      oldPrice: 850,
    },
    {
      id: 2,
      name: "فيلر للشفايف ٥مج",
      type: "cosmetics",
      price: 1500,
    },
    {
      id: 3,
      name: "فيلر للوجه ١مل",
      type: "cosmetics",
      price: 1500,
    },
    {
      id: 4,
      name: "فيلر للوجه ٢مل",
      type: "cosmetics",
      price: 2500,
    },
    {
      id: 5,
      name: "فيلر للوجه ٣مل",
      type: "cosmetics",
      price: 3500,
    },
    {
      id: 6,
      name: "فيلر للوجه ٤مل",
      type: "cosmetics",
      price: 4500,
    },
    {
      id: 7,
      name: "علاج حب الشباب",
      type: "dermatology",
      price: 500,
    },
    {
      id: 8,
      name: "علاج البهاق",
      type: "dermatology",
      price: 1000,
    },
    {
      id: 9,
      name: "علاج تساقط الشعر",
      type: "dermatology",
      price: 800,
    },
    {
      id: 10,
      name: "تنظيف البشرة",
      type: "dermatology",
      price: 300,
    },
    {
      id: 11,
      name: "تقشير البشرة",
      type: "dermatology",
      price: 400,
    },
    {
      id: 12,
      name: "تجميل الأسنان",
      type: "cosmetics",
      price: 2000,
    },
    {
      id: 13,
      name: "تبييض الأسنان",
      type: "cosmetics",
      price: 1500,
    },
    {
      id: 14,
      name: "زراعة الشعر",
      type: "cosmetics",
      price: 5000,
    },
    {
      id: 15,
      name: "تجميل الشفايف",
      type: "cosmetics",
      price: 1200,
    },
    {
      id: 16,
      name: "إزالة الشعر بالليزر",
      type: "laser",
      price: 600,
    },
    {
      id: 17,
      name: "تجديد البشرة بالليزر",
      type: "laser",
      price: 900,
    },
    {
      id: 18,
      name: "إزالة الوشم بالليزر",
      type: "laser",
      price: 800,
    },
    {
      id: 19,
      name: "علاج حب الشباب بالليزر",
      type: "laser",
      price: 700,
    },
    {
      id: 20,
      name: "تفتيح البشرة بالليزر",
      type: "laser",
      price: 1000,
    },
  ];