import type { Metadata } from "next";
import Footer from "../components/Footer";
import "./globals.css";
import "react-image-gallery/styles/css/image-gallery.css";
import 'react-alice-carousel/lib/alice-carousel.css' 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Cairo:wght@200..1000&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="overflow-x-hidden">
        {children} <Footer />
      </body>
    </html>
  );
}
