export const services = [
  {
    id: 1,
    name: "ابر النضارة للوجه والبشرة",
    type: "cosmetics",
    price: 350,
    oldPrice: 850,
    description:
      "إبرة النضارة الفرنسية NCTF عبارة عن محلول من حمض الهيالورونيك أسيد بتركيز عالي، تتكون تركيبته من 59 مجموعة من الفيتامينات والمعادن اللازمة لتحفيز التنشيط الميزوثيرابي والتنشيط البيولوجي للبشرة المرهقة لاستعادة مرونتها المفقودة وتخليصها من التجاعيد والتصبغات والمسامات الواسعة.",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
  },
  {
    id: 2,
    name: "فيلر للشفايف ٥مج",
    type: "cosmetics",
    price: 1500,
    description: "أحدث التقنيات لتعزيز حجم وشكل الشفاه بطريقة طبيعية.",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
  },
  {
    id: 3,
    name: "فيلر للوجه ١مل",
    type: "cosmetics",
    price: 1500,
    description: "حقن الفيلر لإضفاء الامتلاء والشباب على الوجه.",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
  },
  {
    id: 4,
    name: "فيلر للوجه ٢مل",
    type: "cosmetics",
    price: 2500,
    description: "إجراء تجميلي يستخدم لتجديد شباب الوجه عن طريق إضافة حجم.",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
  },
  {
    id: 5,
    name: "فيلر للوجه ٣مل",
    type: "cosmetics",
    price: 3500,
    description: "تقنية متقدمة لتعزيز جمال الوجه وملئ التجاويف بالفيلر.",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
  },
  {
    id: 6,
    name: "فيلر للوجه ٤مل",
    type: "cosmetics",
    price: 4500,
    description: "علاج فعّال يؤدي إلى استعادة حيوية الوجه وشبابه من خلال فيلر.",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
  },
  {
    id: 7,
    name: "علاج حب الشباب",
    type: "dermatology",
    price: 500,
    description: "طرق متنوعة وفعّالة لعلاج حب الشباب وآثاره.",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
  },
  {
    id: 8,
    name: "علاج البهاق",
    type: "dermatology",
    price: 1000,
    description: "بروتوكولات علاجية لمواجهة البهاق وتحسين مظهر البشرة.",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
  },
  {
    id: 9,
    name: "علاج تساقط الشعر",
    type: "dermatology",
    price: 800,
    description: "حلول متخصصة لإيقاف تساقط الشعر وتحفيز نموه مجدداً.",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
  },
  {
    id: 10,
    name: "تنظيف البشرة",
    type: "dermatology",
    price: 300,
    description: "خدمات تنظيف البشرة العميق للحفاظ على صحتها ونقائها.",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
  },
  {
    id: 11,
    name: "تقشير البشرة",
    type: "dermatology",
    price: 400,
    description: "تقشير دقيق للبشرة لإزالة الخلايا الميتة وتجديد شباب الجلد.",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
  },
  {
    id: 12,
    name: "تجميل الأسنان",
    type: "cosmetics",
    price: 2000,
    description: "احصل على ابتسامة جذابة مع أحدث طرق تجميل الأسنان.",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
  },
  {
    id: 13,
    name: "تبييض الأسنان",
    type: "cosmetics",
    price: 1500,
    description: "تقنيات متقدمة للحصول على أسنان أكثر بياضاً ولمعاناً.",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
  },
  {
    id: 14,
    name: "زراعة الشعر",
    type: "cosmetics",
    price: 5000,
    description: "استعادة الشعر الكثيف مع أفضل تقنيات زراعة الشعر.",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
  },
  {
    id: 15,
    name: "تجميل الشفايف",
    type: "cosmetics",
    price: 1200,
    description: "تعديل وتحسين مظهر الشفايف لابتسامة أجمل وأكثر تناسقاً.",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
  },
  {
    id: 16,
    name: "إزالة الشعر بالليزر",
    type: "laser",
    price: 600,
    description: "تجربة إزالة شعر ناعمة ودائمة باستخدام أحدث أجهزة الليزر.",
    images: [
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
      "https://via.placeholder.com/150",
    ],
  },
];
